[package]
name = "attempt9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "attempt9"
path = "attempt9.rs"

[profile.release]
debug = true